include:
  - project: 'common/ci-utils'
    file:
      - '/templates/.add-ssh-key.yml'
      - '/templates/.add-aws-key.yml'

.scripts:
  deps:
    - apt update
    - apt upgrade -y
    - apt remove cmake
    - apt install -y git build-essential
    - pip install cmake

  ci-build:
    - pip install cibuildwheel==2.22.0
    - cibuildwheel --output-dir wheelhouse

# cibuildwheel SEE: https://cibuildwheel.pypa.io/en/stable/setup/#gitlab-ci

  cmake:
    - mkdir build && cd build
    - cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DPOEM_BUILD_TESTS=$ENABLE_TEST
      -DPOEM_BUILD_TOOLS=ON
      -DPOEM_ALLOW_DIRTY=OFF
      -DPOEM_BUILD_PYTHON=ON
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$(pwd)

  awscli:
    - pip install awscli
    - mkdir -p $HOME/.aws
    - echo "[default]" > $HOME/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials



test:
  #  except:
  #    - tags  # don't run the tests on tags
  image: "python:$PYTHON_VERSION-bullseye"

  variables:
    PYTHON_VERSION: "3.10"
    ENABLE_TEST: "ON"

  before_script:
    - !reference [.add-ssh-key, before_script]
    - !reference [.scripts, deps]
    - !reference [ .scripts, awscli ]
  script:
    - !reference [.scripts, cmake]
    - make poem_tests -j6
    - cd bin/tests
    - ./poem_tests


.build:
#  only:
#    - tags
  image: "python:$PYTHON_VERSION-bullseye"

  before_script:
    - !reference [.add-ssh-key, before_script]
    - !reference [.scripts, deps]
    - !reference [.scripts, ci-build]

  script:
    - !reference [.scripts, cmake]
    - make pypoem -j6
    - ls


python312:
  variables:
    PYTHON_VERSION: "3.12"
    ENABLE_TEST: "OFF"
  extends:
    - .build





#.build:
#
#  image: "python:$PYTHON_VERSION-bullseye"
#
#  variables:
#    PYTHON_VERSION:
#
#  before_script:
#    - !reference [ .add-ssh-key, before_script ]
#    - !reference [ .script, deps]
##    - !reference [ .add-aws-key, before_script ]
#    - apt update
#    - apt remove cmake
#    - apt install -y python3 python3-pip git
#    - pip install cmake
#
#  script:


#build-testing:
#
#  image: ubuntu:20.04
#
#  before_script:
#    - !reference [ .build, before_script ]
#
#  script:
#    - !reference [ .build, script ]
#    - make poem_tests -j6
#    - cd bin/tests
#    - ./poem_tests
