include:
  - project: 'common/ci-utils'
    file:
      - '/templates/.add-ssh-key.yml'
      - '/templates/.add-aws-key.yml'

.scripts:
  deps:
    - apt update
    - apt upgrade -y
    - apt remove cmake
    - apt install -y git build-essential
    - pip install cmake

#  ci-build:
#    - pip install cibuildwheel==2.22.0
#    - cibuildwheel --output-dir wheelhouse

# cibuildwheel SEE: https://cibuildwheel.pypa.io/en/stable/setup/#gitlab-ci

  cmake:
    - mkdir build && cd build
    - cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DPOEM_BUILD_TESTS=$ENABLE_TEST
      -DPOEM_BUILD_TOOLS=ON
      -DPOEM_ALLOW_DIRTY=OFF
      -DPOEM_BUILD_PYTHON=ON
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$(pwd)

  awscli:
    - pip install awscli
    - mkdir -p $HOME/.aws
    - echo "[default]" > $HOME/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials



test:
  only:
    - tags # TODO: retirer
  #  except:
  #    - tags  # don't run the tests on tags
  image: "python:$PYTHON_VERSION-bullseye" # TODO: on pourra prendre une debian autre...

  variables:
    PYTHON_VERSION: "3.10"
    ENABLE_TEST: "ON"

  before_script:
    - !reference [.add-ssh-key, before_script]
    - !reference [.scripts, deps]
    - !reference [ .scripts, awscli ]
  script:
    - !reference [.scripts, cmake]
    - make poem_tests -j6
    - cd bin/tests
    - ./poem_tests


essai:
  image: python:3.12-bullseye
  services:
    - docker:dind # using Docker In Docker as a service
#      entrypoint: [ "env", "-u", "DOCKER_HOST" ]
#    - command: [ "dockerd-entrypoint.sh" ]


  variables:
    SSH_PRIVATE_KEY: $GITLAB_CI_SSH_PRIVATE_KEY
    CIBW_BEFORE_ALL: >
      yum install -y openssh-clients &&
      eval $(ssh-agent -s) &&
      mkdir -p ~/.ssh &&
      echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa &&
      chmod 700 ~/.ssh &&
      chmod 700 ~/.ssh/id_rsa &&
      echo "$GITLAB_CI_SSH_KNOWN_HOST" | tr -d '\r' > ~/.ssh/known_hosts &&
      pip install cmake &&
      cmake --version &&
      yum install -y graphviz
      
      

  before_script:
    - !reference [ .add-ssh-key, before_script ]
#    - echo "$GITLAB_CI_SSH_PRIVATE_KEY"
    - curl -sSL https://get.docker.com/ | sh # install docker

  script:
#    - docker info
#    - docker run hello-world
#    - python --version
    - pip install --upgrade pip
    - pip install cibuildwheel==2.22.0
#    - cibuildwheel --print-build-identifiers
    - cibuildwheel --output-dir linuxwheels --platform linux