include:
  - project: 'common/ci-utils'
    file:
      - '/templates/.add-ssh-key.yml'
      - '/templates/.add-aws-key.yml'
  - 'ci-utils/.cpppoem.yml'
  - 'ci-utils/.pypoem.yml'

stages:
  - build
  - deploy

#linux
cpp-linux-tests:
  extends:
    - .cpppoem-linux
    - .cpppoem-tests

pypoem-linux-tests:
  extends: 
    - .pypoem-linux
    - .pypoem-tests
  variables:
    CIBW_BUILD: cp312-manylinux_x86_64

pypoem-linux-multiversion:
  extends:
    - .pypoem-linux
    - .pypoem-multiversion
  variables:
    CIBW_BUILD: cp3*-manylinux_x86_64

pypi-linux-deploy:
  extends:
    - .pypoem-linux
    - .pypoem-deploy

#windows
cpp-windows-tests:
  extends:
    - .cpppoem-windows
    - .cpppoem-tests

pypoem-windows-tests:
  extends:
    - .pypoem-windows 
    - .pypoem-tests
  variables:
    CIBW_BUILD: cp313-win_amd64

pypoem-windows-multiversion:
  extends:
    - .pypoem-windows 
    - .pypoem-multiversion
  variables:
    CIBW_BUILD: cp3*-win_amd64

pypi-windows-deploy:
  extends:
    - .pypoem-windows
    - .pypoem-deploy
