# smichel: test ci following weval as a 'template'
.scripts:
  sshconfig:
    # check this out: https://docs.gitlab.com/ee/ci/ssh_keys/
    - 'which ssh-agent || ( apt update -y && apt install -y openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 700 ~/.ssh/id_rsa
    - ssh-add
    # also add the known hosts so we don't have to accept when connecting to the host
    - echo "$GITLAB_CI_SSH_KNOWN_HOST" | tr -d '\r' > ~/.ssh/known_hosts
    
  deps:
    - apt update
    # - apt install -y git build-essential
    - apt remove cmake
    - apt install -y python3 python3-pip git build-essential libboost-dev
    - pip install cmake
    - pip install pybind11[global]
    # - apt-get install libz-dev

  awscli:
    - pip install awscli
    - mkdir -p $HOME/.aws
    - echo "[default]" > $HOME/.aws/credentials
    - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
    - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials
    
  cmake:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -Dpoem_enable_tests=$ENABLE_TEST -Dpoem_build_tools=OFF -Dpoem_allow_dirty=OFF ..
    - make -j6

  upload:
    - OUTPUT=$(echo "pypoem.cpython-$(echo $PYTHON_VERSION | sed -r 's/[.]//g')-x86_64-linux-gnu.so")
    - echo "Uploading $OUTPUT to s3"
    - aws s3 cp src/pypoem/$OUTPUT s3://dice-code/$CI_PROJECT_NAME/$CI_COMMIT_TAG/



test:
  except:
    - tags  # don't run the tests on tags
  image: "python:$PYTHON_VERSION-bullseye"

  variables:
    PYTHON_VERSION: "3.10"
    ENABLE_TEST: "ON"
  before_script:
    - !reference [.scripts, sshconfig]
    - !reference [.scripts, deps]
    - !reference [.scripts, awscli]
    - !reference [.scripts, cmake]
  script:
    # c++ tests
    - make -j6
    - ./bin/tests/test_read_poem
    # - cd ..
    # - pip install -r requirements-dev.txt
    # - pip install .
    # - pytest --log-level=INFO test/

.build:
  only:
    - tags
  image: "python:$PYTHON_VERSION-bullseye"

  before_script:
    - !reference [.scripts, sshconfig]
    - !reference [.scripts, deps]
    - !reference [.scripts, awscli]
    - !reference [.scripts, cmake]
  script:
    - make pypoem
    - !reference [.scripts, upload]

python312:
  variables:
    PYTHON_VERSION: "3.12"
    ENABLE_TEST: "OFF"
  extends:
    - .build

python311:
  variables:
    PYTHON_VERSION: "3.11"
    ENABLE_TEST: "OFF"
  extends:
    - .build

python310:
  variables:
    PYTHON_VERSION: "3.10"
    ENABLE_TEST: "OFF"
  extends:
    - .build

python39:
  variables:
    PYTHON_VERSION: "3.9"
    ENABLE_TEST: "OFF"
  extends:
    - .build
