# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

import datetime
# import wools
# import pkgutil
# import importlib

year = datetime.datetime.now().year

# version = wools.__version__


# -- Project information -----------------------------------------------------

project = 'POEM'
copyright = '%s, D-ICE ENGINEERING' % year
# author = 'D-ICE WASP TEAM'

# The full version, including alpha/beta/rc tags
# release = wools.__version__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    #    'sphinx_numfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.graphviz',
    # 'sphinxarg.ext',
    #    'sphinxcontrib.programoutput',
    #    'sphinxcontrib.bibtex',
    'sphinx.ext.autosummary'
]

# Napoleon settings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

html_logo = '_static/D-ICE-blanc.png'
html_favicon = '_static/dice-favicon.png'

html_theme_options = {
#     # 'analytics_id': 'G-XXXXXXXXXX',  #  Provided by Google in your dashboard
#     # 'analytics_anonymize_ip': False,
#     # 'logo_only': False,
#     'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
#     'vcs_pageview_mode': '',
#     # 'style_nav_header_background': 'white',
#     # 'flyout_display': 'hidden',
#     # 'version_selector': True,
#     # 'language_selector': True,
#     # Toc options
    'collapse_navigation': False,
#     'sticky_navigation': False,
    'navigation_depth': 3,
#     'includehidden': True,
#     'titles_only': True
}

# Numbering of figures, tables, etc.
numfig = True

# -- Options for maths -------------------------------------------------------

math_number_all = True
# math_numfig = True
# numfig_secnum_depth = 3
math_eqref_format = "Eq.{number}"
html_math_renderer = "mathjax"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',
    #
    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt',
    #
    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
\usepackage{chngcntr}
\counterwithin{figure}{chapter}
\counterwithin{table}{chapter}''',
    #
    # Latex figure (float) alignment
    #
    'figure_align': 'H',
    'releasename': '[CONFIDENTIAL]'
}

latex_logo = '_static/D-ICE-v.png'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'poem.tex', u'poem',
     u'D-ICE Engineering', 'manual'),
]
