include(FetchContent)

FetchContent_Declare(netcdf-c
        URL ${netcdf-c_URL}
        PATCH_COMMAND patch -p1 < ${PROJECT_SOURCE_DIR}/cmake/patches/${netcdf-c_PATCH}
        )

# netcdf-c BUILD OPTIONS
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(USE_HDF5 ON CACHE BOOL "" FORCE)
set(ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_UNIT_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_PARALLEL_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_FILTER_TESTING OFF CACHE BOOL "" FORCE)
set(ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_UTILITIES OFF CACHE BOOL "" FORCE)
set(ENABLE_HDF4_FILE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_DAP_REMOTE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_NCZARR OFF CACHE BOOL "" FORCE)
set(ENABLE_DAP OFF CACHE BOOL "" FORCE)

message(STATUS "******* FETCHING netcdf-c dependency from ${PROJECT_NAME} (requested version: ${netcdf-c_TAG}) *******")
FetchContent_MakeAvailable(netcdf-c)

set_property(TARGET dispatch PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET netcdf3 PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET netcdf4 PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET netcdfhdf5 PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET netcdf PROPERTY POSITION_INDEPENDENT_CODE ON)
